# Generated by Django 4.1.9 on 2023-06-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(blank=True, default=None)),
                ('square_meters', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('renovated', models.BooleanField(blank=True, default=False)),
                ('shelter_inside', models.BooleanField(blank=True, default=False)),
                ('shelter_nearby', models.BooleanField(blank=True, default=False)),
                ('furnished', models.BooleanField(blank=True, default=False)),
                ('shared_livingroom', models.BooleanField(blank=True, default=False)),
                ('rooms_number', models.FloatField(default=None, max_length=3)),
                ('roomates_number', models.IntegerField(default=None)),
                ('showers_number', models.IntegerField(default=None)),
                ('toilets_number', models.IntegerField(default=None)),
                ('Location', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_for_profile.jpg', help_text='Choose your profile-picture', upload_to=functools.partial(users.models.image_upload_path, *(), **{'flag': 1}))),
                ('profile_status', models.CharField(choices=[('StatusInsert', 'insert in'), ('StatusEnter', 'enter in')], default=' ', help_text='What you are looking for', max_length=15)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('birthdate', models.DateField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter a valid phone number (e.g. +972521111111)', max_length=128, region=None)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender'), ('NB', 'Non-binary'), ('GN', 'Gender neutral'), ('D', "Don't wish to answer")], max_length=10)),
                ('occupation', models.CharField(blank=True, choices=[('F', 'Full-time job'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Don't wish to answer")], max_length=30)),
                ('smoker', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('D', "Don't wish to answer")], max_length=15)),
                ('diet', models.CharField(blank=True, choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism'), ('D', "Don't wish to answer")], max_length=15)),
                ('status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('D', "Don't wish to answer")], max_length=20)),
                ('hospitality', models.CharField(blank=True, choices=[('L', 'Love'), ('N', 'Prefer not'), ('D', "Don't wish to answer")], default='', max_length=15)),
                ('kosher', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('D', "Doesn't matter")], max_length=15)),
                ('expense_management', models.CharField(blank=True, choices=[('S', 'Shared'), ('I', 'Individual'), ('D', "Doesn't matter")], max_length=15)),
                ('about_me', models.TextField(blank=True, default='', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_for_property.jpg', upload_to=functools.partial(users.models.image_upload_path, *(), **{'flag': 0}))),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.propertyforoffer')),
            ],
        ),
    ]
