# Generated by Django 4.1.7 on 2023-04-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Diet',
            field=models.CharField(choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism')], default='Carnivors', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='Expense_Management',
            field=models.CharField(choices=[('Y', 'Prefer'), ('N', 'Prefer not')], default='N', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='Hospitality',
            field=models.CharField(choices=[('L', 'Love'), ('N', 'Prefer not')], default='L', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='Kosher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Occupation',
            field=models.CharField(choices=[('F', 'Full-time jobe'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter")], default='D', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Smoker',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially')], default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('D', "Doesn't matter")], default='D', max_length=20),
        ),
    ]
