# Generated by Django 4.1.7 on 2023-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforoffer',
            name='rent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
