# Generated by Django 4.1.7 on 2023-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_for_profile.jpg', help_text='Choose your profile-picture', upload_to='profile_pics'),
        ),
    ]
