# Generated by Django 4.1.7 on 2023-04-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birthdate_profile_diet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Diet',
            new_name='diet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Expense_Management',
            new_name='expense_management',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Hospitality',
            new_name='hospitality',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Kosher',
            new_name='kosher',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Smoker',
            new_name='smoker',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Status',
            new_name='status',
        ),
    ]
