# Generated by Django 4.1.7 on 2023-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyforoffer',
            old_name='shelter_nerbay',
            new_name='shelter_nearby',
        ),
        migrations.AddField(
            model_name='propertyforoffer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='propertyforoffer',
            name='country',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='propertyforoffer',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
