# Generated by Django 4.1.7 on 2023-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_propertyforoffer_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforoffer',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='propertyforoffer',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='propertyforoffer',
            name='neighborhood',
            field=models.CharField(default='', max_length=25),
        ),
    ]
