# Generated by Django 4.1.7 on 2023-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_image_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='default_for_property.png', null=True, upload_to='property_pics'),
        ),
    ]
