# Generated by Django 4.1.7 on 2023-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_birthdate_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.CharField(choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism'), ('empty', '---')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expense_management',
            field=models.CharField(choices=[('Y', 'Prefer'), ('N', 'Prefer not'), ('empty', '---')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined'), ('empty', '---')], default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospitality',
            field=models.CharField(choices=[('L', 'Love'), ('N', 'Prefer not'), ('empty', '---')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('F', 'Full-time jobe'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter"), ('empty', '---')], default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoker',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially'), ('empty', '---')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('D', "Doesn't matter"), ('empty', '---')], default='empty', max_length=20),
        ),
    ]
