# Generated by Django 4.1.7 on 2023-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_diet_alter_profile_expense_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined'), ('empty', '---')], default='empty', max_length=10),
        ),
    ]
