# Generated by Django 4.1.7 on 2023-04-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kosher',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('empty', '---')], default='empty', max_length=15),
        ),
    ]
