# Generated by Django 4.1.7 on 2023-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_kosher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('StatusInsert', 'Roomate'), ('StatusEnter', 'Appartment')], default=' ', help_text='What are you looking for', max_length=15),
        ),
    ]
