# Generated by Django 4.2 on 2023-05-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_score', models.FloatField()),
                ('Insert_score', models.FloatField()),
                ('Username_enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_entered', to=settings.AUTH_USER_MODEL)),
                ('Username_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_inserted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsR',
            fields=[
                ('Requirement_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Occupation', models.CharField(blank=True, choices=[('F', 'Full-time job'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter"), ('empty', '---')], default=None, max_length=30, null=True)),
                ('MinAge', models.IntegerField(blank=True, default=None, null=True)),
                ('MaxAge', models.IntegerField(blank=True, default=None, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], default=None, max_length=10, null=True)),
                ('Smoker', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially')], default=None, max_length=15, null=True)),
                ('Diet', models.CharField(blank=True, choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism')], default=None, max_length=15, null=True)),
                ('Kosher', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=15, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('D', "Doesn't matter")], default=None, max_length=20, null=True)),
                ('Weight', models.FloatField(blank=True, default=14.285714285714286, null=True)),
                ('Expense_Management', models.CharField(choices=[('L', 'Love'), ('P', 'Prefer not')], default='P', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsP',
            fields=[
                ('Requirement_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('P', 'Property'), ('R', 'Roommate')], max_length=1)),
                ('Country', models.CharField(blank=True, default='', max_length=25)),
                ('City', models.CharField(blank=True, default='', max_length=25)),
                ('Neighborhood', models.CharField(blank=True, default='', max_length=25)),
                ('MinRent', models.IntegerField(blank=True, default=None, null=True)),
                ('MaxRent', models.IntegerField(blank=True, default=None, null=True)),
                ('MinRooms', models.IntegerField(blank=True, default=None, null=True)),
                ('MaxRooms', models.IntegerField(blank=True, default=None, null=True)),
                ('MaxRoommates', models.IntegerField(blank=True, default=None, null=True)),
                ('MinRoommates', models.IntegerField(blank=True, default=None, null=True)),
                ('MinToilets', models.IntegerField(blank=True, default=None, null=True)),
                ('MinShowers', models.IntegerField(blank=True, default=None, null=True)),
                ('Weight', models.FloatField(blank=True, default=20.0, null=True)),
                ('Renovated', models.BooleanField(blank=True, default=False)),
                ('Shelter_Inside', models.BooleanField(blank=True, default=False)),
                ('Shelter_Nearby', models.BooleanField(blank=True, default=False)),
                ('Furnished', models.BooleanField(blank=True, default=False)),
                ('Shared_Living_Room', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_likes_insert', models.BooleanField(default=False)),
                ('insert_likes_enter', models.BooleanField(default=False)),
                ('User_enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insert_likes_enter', to=settings.AUTH_USER_MODEL)),
                ('User_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_likes_insert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scores',
            constraint=models.UniqueConstraint(fields=('Username_enter', 'Username_insert'), name='unique_scores'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('User_insert', 'User_enter'), name='unique_likes'),
        ),
    ]
