# Generated by Django 4.1.7 on 2023-04-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='User_ID',
            new_name='ID',
        ),
    ]
