# Generated by Django 4.1.7 on 2023-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='enter_likes_insert',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='likes',
            name='insert_likes_enter',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
