# Generated by Django 4.1.7 on 2023-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementsp',
            name='Shared_Living_Room',
        ),
        migrations.RemoveField(
            model_name='requirementsp',
            name='Shelter_Inside',
        ),
        migrations.RemoveField(
            model_name='requirementsp',
            name='Shelter_Nearby',
        ),
        migrations.RemoveField(
            model_name='requirementsp',
            name='Type',
        ),
        migrations.AddField(
            model_name='requirementsp',
            name='SharedLivingRoom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementsp',
            name='ShelterInside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementsp',
            name='ShelterNearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Hospitality',
            field=models.CharField(blank=True, choices=[('L', 'Love'), ('N', 'Prefer not')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='requirementsp',
            name='Furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requirementsp',
            name='Renovated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requirementsp',
            name='Weight',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Weight',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
