# Generated by Django 4.1.9 on 2023-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsp',
            name='Location',
            field=models.TextField(blank=True),
        ),
    ]
