# Generated by Django 4.1.7 on 2023-05-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Birthdate', models.DateField(blank=True, null=True)),
                ('Phone_Number', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], max_length=10)),
                ('Occupation', models.CharField(choices=[('F', 'Full-time jobe'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter")], default='D', max_length=30)),
                ('Smoker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially')], max_length=15)),
                ('Diet', models.CharField(choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism')], max_length=15)),
                ('Status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship')], max_length=20)),
                ('Hospitality', models.BooleanField(default=True, max_length=15)),
                ('Kosher', models.BooleanField(default=False)),
                ('Expense_Management', models.CharField(choices=[('L', 'Love'), ('P', 'Prefer not')], default='P', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Roommates',
            fields=[
                ('Roommate_ID', models.FloatField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('StatusInsert', 'StatusInsert'), ('StatusEnter', 'StatusEnter')], max_length=50)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Hospitality',
            field=models.CharField(blank=True, choices=[('L', 'Love'), ('N', 'Prefer not')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Weight',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.CreateModel(
            name='StatusInsert',
            fields=[
                ('ID', models.FloatField(primary_key=True, serialize=False)),
                ('Target', models.CharField(choices=[('P', 'P'), ('R', 'R')], max_length=1)),
                ('Content', models.CharField(max_length=150)),
                ('Roommate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomit_app.roommates')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEnter',
            fields=[
                ('Status_ID', models.FloatField(primary_key=True, serialize=False)),
                ('Target', models.CharField(choices=[('P', 'P'), ('R', 'R')], max_length=1)),
                ('Content', models.CharField(max_length=150)),
                ('Roommate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomit_app.roommates')),
            ],
        ),
    ]
