# Generated by Django 4.2 on 2023-05-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0002_likes_likes_unique_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommates',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='statusenter',
            name='Roommate_ID',
        ),
        migrations.RemoveField(
            model_name='statusinsert',
            name='Roommate_ID',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Roommates',
        ),
        migrations.DeleteModel(
            name='StatusEnter',
        ),
        migrations.DeleteModel(
            name='StatusInsert',
        ),
    ]
