# Generated by Django 4.1.7 on 2023-04-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0002_rename_user_id_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Birthday',
            new_name='Birthdate',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Employment',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Roommate_ID',
        ),
        migrations.RemoveField(
            model_name='roommates',
            name='Picture',
        ),
        migrations.AddField(
            model_name='info',
            name='Kosher',
            field=models.BooleanField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='info',
            name='Occupation',
            field=models.CharField(choices=[('F', 'Full-time jobe'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter")], default='D', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='Expense_Management',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='Hospitality',
            field=models.BooleanField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='Info_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='roomit_app.users'),
        ),
        migrations.AlterField(
            model_name='info',
            name='Status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
