# Generated by Django 4.1.7 on 2023-05-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0002_info_roommates_requirementsr_hospitality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommates',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='statusenter',
            name='Roommate_ID',
        ),
        migrations.RemoveField(
            model_name='statusinsert',
            name='Roommate_ID',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Roommates',
        ),
        migrations.DeleteModel(
            name='StatusEnter',
        ),
        migrations.DeleteModel(
            name='StatusInsert',
        ),
    ]
