# Generated by Django 4.1.7 on 2023-04-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0003_rename_birthday_info_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Info_ID',
            new_name='User_ID',
        ),
        migrations.AlterField(
            model_name='info',
            name='Expense_Management',
            field=models.CharField(choices=[('L', 'Love'), ('P', 'Prefer not')], default='P', max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='Kosher',
            field=models.BooleanField(default=False),
        ),
    ]
