# Generated by Django 4.1.7 on 2023-05-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0003_remove_roommates_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementsp',
            name='Type',
        ),
    ]
