# Generated by Django 4.2 on 2023-04-18 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0006_requirementsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsp',
            name='Requirement_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requirementsp',
            name='Roommates_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
