# Generated by Django 4.2 on 2023-04-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0008_alter_requirementsp_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementsp',
            old_name='Roommates_ID',
            new_name='user',
        ),
    ]
