# Generated by Django 4.2 on 2023-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0010_requirementsp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsp',
            name='MinShowers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
