# Generated by Django 4.2 on 2023-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0013_requirementsr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsr',
            name='Diet',
            field=models.CharField(blank=True, choices=[('Carnivore', 'Carnivore'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Raw Veganism', 'Raw Veganism')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Kosher',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Occupation',
            field=models.CharField(blank=True, choices=[('F', 'Full-time job'), ('S', 'Student'), ('P', 'Part-time job'), ('D', "Doesn't matter"), ('empty', '---')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Smoker',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally'), ('Socially', 'Socially')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='requirementsr',
            name='Status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('D', "Doesn't matter")], default=None, max_length=20, null=True),
        ),
    ]
