# Generated by Django 4.2 on 2023-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0014_alter_requirementsr_diet_alter_requirementsr_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsr',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not Defined')], default=None, max_length=10, null=True),
        ),
    ]
