# Generated by Django 4.2 on 2023-04-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0015_alter_requirementsr_gender'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scores',
            name='unique_scores',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='Roommate',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='Roommates_ID',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='Roommate1_ID',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='Roommate2_ID',
        ),
        migrations.AddField(
            model_name='offers',
            name='City',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='offers',
            name='Country',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='offers',
            name='Neighborhood',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='offers',
            name='Rent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='Roomates',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='Rooms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='Showers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='Toilets',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scores',
            name='Username1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roommate1_scores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scores',
            name='Username2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roommate2_scores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='Offer_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='scores',
            constraint=models.UniqueConstraint(fields=('Username1', 'Username2'), name='unique_scores'),
        ),
    ]
