# Generated by Django 4.2 on 2023-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0016_remove_scores_unique_scores_remove_offers_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsp',
            name='Weight',
            field=models.FloatField(blank=True, default=16.666666666666668, null=True),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Weight',
            field=models.FloatField(blank=True, default=14.285714285714286, null=True),
        ),
    ]
