# Generated by Django 4.2 on 2023-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0017_requirementsp_weight_requirementsr_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='Total_Score',
        ),
        migrations.AlterField(
            model_name='requirementsp',
            name='Weight',
            field=models.FloatField(blank=True, default=20.0, null=True),
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
