# Generated by Django 4.2 on 2023-04-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0018_remove_scores_total_score_alter_requirementsp_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='Roommate1_score',
            new_name='Enter_score',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='Roommate2_score',
            new_name='Insert_score',
        ),
        migrations.AlterField(
            model_name='scores',
            name='Username1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enter_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Username2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insert_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
