# Generated by Django 4.2 on 2023-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0019_rename_roommate1_score_scores_enter_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
