# Generated by Django 4.2 on 2023-04-21 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0020_delete_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_score', models.FloatField()),
                ('Insert_score', models.FloatField()),
                ('Username_enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_entered', to=settings.AUTH_USER_MODEL)),
                ('Username_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_inserted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scores',
            constraint=models.UniqueConstraint(fields=('Username_enter', 'Username_insert'), name='unique_scores'),
        ),
    ]
