# Generated by Django 4.2 on 2023-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0021_scores_scores_unique_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsr',
            name='Expense_Management',
            field=models.CharField(choices=[('L', 'Love'), ('P', 'Prefer not')], default='P', max_length=15),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Renovated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Shared_Living_Room',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Shelter_Inside',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='requirementsr',
            name='Shelter_Nearby',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
