# Generated by Django 4.2 on 2023-04-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomit_app', '0023_remove_requirementsr_furnished_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_likes_insert', models.BooleanField(blank=True, default=False)),
                ('insert_likes_enter', models.BooleanField(blank=True, default=False)),
                ('User_enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insert_likes_enter', to=settings.AUTH_USER_MODEL)),
                ('User_insert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_likes_insert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('User_insert', 'User_enter'), name='unique_likes'),
        ),
    ]
