# Generated by Django 4.2 on 2023-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomit_app', '0024_likes_likes_unique_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='enter_likes_insert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='insert_likes_enter',
            field=models.BooleanField(default=False),
        ),
    ]
